/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.pattern1.controller.Pattern1OpenCsvController;
import app.pattern2.controller.Pattern2OpenCsvController;

public class App {
    
    public static void main(String[] args) {
        if(args[0].equals("1")){
            new Pattern1OpenCsvController(args);
        } else {
            new Pattern2OpenCsvController(args);
        }
    }
}
