/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void test1() {
        // csv出力
        String[] args = {"1","1"};
        App.main(args);       
    }

    @Test 
    public void test2() {
        // csv読み込み
        String[] args = {"1","2"};
        App.main(args);       
    }

    @Test 
    public void test3() {
        // csv出力(Bean)
        String[] args = {"2","1"};
        App.main(args);       
    }

    @Test 
    public void test4() {
        // csv読み込み(Bean)
        String[] args = {"2","2"};
        App.main(args);       
    }
}
