/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.Test;

import app.pattern2.bean.UserInfoBean;
import app.pattern2.bean.UserInfoBean2;
import app.pattern2.util.Pattern2ReadCSVUtil;
import app.pattern2.util.Pattern2WriteCSVUtil;

import static org.junit.Assert.*;

import java.io.FileWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

import com.opencsv.bean.StatefulBeanToCsv;
import com.opencsv.bean.StatefulBeanToCsvBuilder;

public class AppTest {
    @Test 
    public void test1() {
        // csv出力
        String[] args = {"1","1"};
        App.main(args);       
    }

    @Test 
    public void test2() {
        // csv読み込み
        String[] args = {"1","2"};
        App.main(args);       
    }

    @Test 
    public void test3() {
        // csv出力(Bean)
        String[] args = {"2","1"};
        App.main(args);       
    }

    @Test 
    public void test4() {
        // csv読み込み(Bean)
        String[] args = {"2","2"};
        App.main(args);       
    }
}
